baseURL = "https://example.com/"
copyright = "(c) 2017 - 2018 Aos Dabbagh -- All rights reserved."
pygmentsCodeFences = true
pygmentsStyle = "friendly"
theme = "temple"
title = "Temple"
[author]
email = "your@email.com"
gaid = "Your Google Analytics ID"
github = "github"
medium = "mediumUsername"
name = "Temple Theme"
twitter = "twitterID"
[params]
topmenu = "categories"
[taxonomies]
category = "categories"
tag = "tags"
